{% set name = "rpbasicdesign" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9d42e03af416448acc6d5b2e758716ed3671e50bb81eb2bee4d1c94f1331d281

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pysbol2
    - rptools

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
    - cobra
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }}.cli --help
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: Convert rpSBML enzyme info into BASIC construct
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tduigou
    - kenza12
